version: 2
jobs:
  eslint:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        command: |
          cd js/
          npm install
          node_modules/.bin/eslint lib
  black:
    docker:
    - image: circleci/python
    steps:
    - checkout
    - run:
        command: |
          cd
          sudo pip install black
          black --check $(pwd)/



workflows:
  version: 2
  style_check:
    jobs:
    - eslint
    - black