version: 2
jobs:
  eslint:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        command: |
          cd js/
          npm install
          node_modules/.bin/eslint lib


workflows:
  version: 2
  linting:
    jobs:
    - eslint