version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.1
    steps:
    - checkout
    - run: echo "A first hello from me"
  do_my_bidding:
    docker:
    - image: circleci/ruby:2.4.1
    steps:
    - checkout
    - run: echo "I can bend this to my will"


workflows:
  version: 2
  both_jobs:
    jobs:
    - build
    - do_my_bidding